### ISSUE TITLE
Bot creates mini lags in GD, every click.

### ISSUE THREAD

**Issue by nomfodm** [Snopphin/Geometry-Dash-Click-Bot#1]
When bot clicks, geometry dash is lagging. What can I do to reduce lags?

p.s my english is bad, i know.

**Comment by Snopphin** [comment]
I maybe fixed go to newest releases and download new

**Comment by Snopphin** [comment]
i had too lags but now maybe its fixed

**Comment by spinningtoilet0** [comment]
Close this if it is fixed.
