### ISSUE TITLE
Practice crash in 0.8

### ISSUE THREAD

**Issue by luihh** [Snopphin/Geometry-Dash-Click-Bot#3]
When i practice a level the game crashes

**Comment by luihh** [comment]
Other thing, the cursor don't hide when i play a level :v

**Comment by luihh** [comment]
Sorry for my bad English

**Comment by luihh** [comment]
Bruh when i complete a level the game crashes

**Comment by luihh** [comment]
That version have a lot bugs

**Comment by luihh** [comment]
the game crashes for a lot of things :'

**Comment by Snopphin** [comment]
enable in gd menu show cursor
