### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by aanginer** [Snopphin/Geometry-Dash-Click-Bot#9]
I have no sound, I have mega hack v5 and zBot, but even without mega hack, it doesn't play any sound. I'm not sure if this is just my computer so can someone explain

**Comment by aanginer** [comment]
oh yeah im using 1.1, 1.0 worke fine

**Comment by aanginer** [comment]
*worked

**Comment by beastlynuginx** [comment]
I think the problem is that you haven't installed Fmod

**Comment by aanginer** [comment]
I had the wrong version, installed 1.9 and it's working perfectly
